version: "3.8"
services:
  server:
    container_name: electronic_device_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file: ./.env
    networks:
      electronic_device_network:
        ipv4_address: 10.5.0.5

  client:
    container_name: electronic_device_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: ./.env
    networks:
      electronic_device_network:
        ipv4_address: 10.5.0.6
  manager:
    container_name: electronic_device_manager
    build:
      context: ./manager
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    env_file: ./.env
    networks:
      electronic_device_network:
        ipv4_address: 10.5.0.7
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

networks:
  electronic_device_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
